; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/DHT sensor library @ ^1.4.4
	adafruit/Adafruit Unified Sensor @ ^1.1.9
	mirs240x/micro_ros_arduino@^2.0.7-humble
board_microros_distro = jazzy
board_microros_transport = serial
