[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
monitor_speed = 115200
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	adafruit/Adafruit Unified Sensor @ ^1.1.9
	mirs240x/micro_ros_arduino@^2.0.7-humble
    https://github.com/tonton81/FlexCAN_T4.git
board_microros_distro = jazzy
board_microros_transport = serial