
[env:teensy41]
platform         = teensy
board            = teensy41
framework        = arduino

; --- micro-ROS PlatformIO integration (official) ---
; Pull the library directly from GitHub
lib_deps =
  https://github.com/micro-ROS/micro_ros_platformio
  FlexCAN_T4

; Workaround for paths with spaces
extra_scripts = pre:fix_microros.py

; Pick your ROS 2 distro (humble | jazzy | rolling | kilted)
; Use 'jazzy' if your PC runs ROS 2 Jazzy
board_microros_distro    = jazzy

; Transport: serial (default). You can switch to native_ethernet later.
board_microros_transport = serial

; Teensy USB: keep serial for USB CDC
build_flags = -D USB_SERIAL

; Serial monitor convenience
monitor_speed = 115200
